#define SCREEN_WIDTH 256
#define SCREEN_HEIGHT 192
#define ATTR_WIDTH (SCREEN_WIDTH / 8)
#define ATTR_HEIGHT (SCREEN_HEIGHT / 8)
#define SCREEN_BASE (u8 *)0x8000
#define SCREEN_LENGTH 0x1800
#define ATTR_BASE (SCREEN_BASE + SCREEN_LENGTH)
#define ATTR_LENGTH 0x300
